### ISSUE TITLE
Update HTTP client dependency in GeoStore

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2-C027#86]
As per @offtherailz feedback [HERE](https://github.com/geosolutions-it/mapstore2-c027/issues/76#issuecomment-1011926064), we need to upgrade GeoStore dependency as well. 

@shadab-geo I would ask you to do an initial assessment of this upgrade:
- How hard will it be to upgrade GeoStore HTTP client version?
- How good is the test coverage of GeoStore, define a test plan for the upgrade.

In the end, we need a plan and estimate.

**Comment by tdipisa** [comment]
@nmco Thank you. If this is strictly needed to deliver #76, as it probably is, I need an estimate as soon as possible. Just let me know @nmco @shadab-geo

**Comment by nmco** [comment]
Hi @tdipisa, Monday after lunch we will have clear plans and deadlines for this. @shadab-geo is working on this full-time.

**Comment by tdipisa** [comment]
Wonderful @nmco, thank you.

**Comment by shadab-geo** [comment]
PR raised: https://github.com/geosolutions-it/geostore/pull/250
@nmco @tdipisa

**Comment by tdipisa** [comment]
@thank you @shadab-geo. @nmco I've commented here https://github.com/geosolutions-it/geostore/pull/250#issuecomment-1020934016

**Comment by offtherailz** [comment]
After this first step, here I report the results of my investigation.

Current `MapStore2-c027` points to geostore `2.6.0`, and http proxy `1.1.0`.  

In order to get these updates we may decide to: 
1. Upgrate current mapstore to master --> requieres a lot of work and makes the project rely on unstable branch, not suggested
2. Upgrade current mapstore to latest stable (and backport these features, in the current release) --> this require the update of the project (that will be needed in the future anyway)
3. Do only backport and minor release of geostore and http_proxy, and use them only in the mapstore2-c027 project. 

In the 3rd case
- backport and release http_proxy `1.1.2`  
- backport and release geostore `1.7.2` 
- Update this project to:
   - http_proxy:  `1.1.0 `-> `1.1.2`
    -geostore:  `1.6.0` -> `1.7.2` <-- This is a small jump to next minor version. I can not see any breaking change in this. 

What do you think @tdipisa @nmco ?

**Comment by tdipisa** [comment]
@nmco in a call with @offtherailz we have commented [above](https://github.com/geosolutions-it/MapStore2-C027/issues/86#issuecomment-1021190439). The solution for http_proxy is simple but I have some concern about geostore:

> if conflicts with geoStore, evaluate to use exclusions

I understood from @offtherailz that we cannot update the MS project to the latest geostore without updating also to the latest mapstore.  This is something that I wouldn't like to do now for c027 because we are to close to the release and the next major release of MS is too far.  Can we have a quick call as soon as you can for this?

**Comment by tdipisa** [comment]
@nmco as you explaining me in the call, it is not a problem to backport geostore updates. Therefore, let's backport by respecting the usual procedures until geostore v1.6.x that is the version used by the MS project of the client (that means a backport to geostore 1.7.x and 1.6.x beranches). We can finally release geostore v1.6.1 after the test in the client environment.

**Comment by shadab-geo** [comment]
I have raised GeoStore backport PR's:
1.6.x: https://github.com/geosolutions-it/geostore/pull/251
1.7.x: https://github.com/geosolutions-it/geostore/pull/252
@nmco @tdipisa

**Comment by offtherailz** [comment]
I approved both, merged 1.7.x not sure about 1.6.x because github actions was not set for that branch. 
Did you executed tests locally @shadab-geo 
If so, I think we can merge.

**Comment by shadab-geo** [comment]
@offtherailz the build on 1.6.x was failing. I had to update the GeoSolutions repository URL in POM.xml, after which it was built successfully. I have updated the PR.
